### PR TITLE
Added a Magento 2 driver

### PR DESCRIPTION
**Pull request by michielgerritsen**

### CODE REVIEW

**Comment by sschlein** [comment]
Thanks for the PR! Can you also send us 2-3 use-cases for Tinkerwell and Magento? Does it make sense to add a context menu like we have it for Laravel (https://github.com/tinkerwellapp/drivers/blob/master/src/Drivers/LaravelTinkerwellDriver.php#L32)? Magento has powerful CLI and things like flushing the cache could be a common use-case.

**Comment by michielgerritsen** [comment]
Hi @sschlein,

Yeah i was already working on a menu for the CLI commands. I just added that to the PR. The context menu looks like this:

Schermafbeelding 2020-02-02 om 14 10 36

When selecting a command from the list result in this:
Schermafbeelding 2020-02-02 om 14 10 46

This way it is possible to add extra parameters when required.

**Comment by mpociot** [comment]
Thank you for the PR - just as a FYI: because of the added phar stream wrapper dependency, this takes some more time for me to merge, as the added dependency needs to be added in the tinkerwell phar internally.

**Comment by michielgerritsen** [comment]
Yeah i wasn't sure if i could add it or not, but it's the only way to make it work on Magento 2.3. 

@sschlein What kind of use cases are you looking for? How i would use it in real world situations? Or some code examples someone could use? Anything else?

**Pull request merged**
