### PR TITLE
Add Infection Driver

### PR DESCRIPTION
**Pull request by maks-rafalko**
* see https://github.com/infection/infection

Not sure if this is enough to check `bin/infection` as other projects that *uses* Infection may also have this file.

Tinkerwell - infection 2

### CODE REVIEW

**Comment by mpociot** [comment]
Thanks for the PR. Can you tell me when this driver should be used? Is it only used when working with the infection codebase itself?

**Comment by maks-rafalko** [comment]
Yes, as this is not a framework but a tool (like phpstan, phpunit, etc.)

**Comment by mpociot** [comment]
Yeah I see. 
Maybe it would then be better to include the driver in your codebase in a .tinkerwell folder as I think that might be more helpful. 
If someone is using infection in a project, this driver would be used as well - even though a framework specific driver might be the better pick.

**Comment by maks-rafalko** [comment]
I thought about it, however I don't think adding proprietary config files to the OSS repository is the right way.

I can be the only one who uses Tinkerwell from all the contributors and I they may not want to see any committed code not related to the project itself.

On the other side, I would avoid adding it to `.gitignore` as it will be definitely missed at some point and I would like to reuse the driver whenever I am.

What do you think about adding some kind of priority to the interface of the driver so that such tools' drivers can be loaded the last?

**Comment by mpociot** [comment]
Okay makes sense. Maybe the bootstrap detection should be improved then so that it doesn’t accidentally get loaded. At least I’d prefer that over adding some kind of priority logic.

**Comment by maks-rafalko** [comment]
> Maybe the bootstrap detection should be improved then so that it doesn’t accidentally get loaded.

Do you mean I need to improve `bootstrap()` method here to make it more "strict"?

**Comment by mpociot** [comment]
I mean the “ canBootstrap” method. Can this be modified so that it’s stricter and will only return true for the infection codebase itself and not when someone might use infection in a project in that directory?

**Comment by maks-rafalko** [comment]
I've added a check for `infection-debug` file that is not available when ifection is installed as a composer package.

**Comment by mpociot** [comment]
Okay perfect, thanks!
I need to release a new Tinkerwell Version so that the new driver is included in the next release.

**Comment by maks-rafalko** [comment]
Thank you!

**Pull request merged**
